name: pine64
version: 16.04-3
summary: Pine64 support package
description: |
 Support files for booting Pine64
type: gadget
architectures:
    - arm64
confinement: strict
grade: stable
parts:
    prebuilt:
        plugin: dump
        source: prebuilt
